export const IPC_ROUTER_CHANNEL = 'IPC_ROUTER_CHANNEL' as const;
export const IPC_SCRIPTS_CHANNEL = 'IPC_SCRIPTS_CHANNEL' as const;
export const CROSS_WINDOW_CHANNEL = 'CROSS_WINDOW_CHANNEL' as const;
